CL\Slack\Payload\FilesListPayload:
    properties:
        user:
            type: string
        tsFrom:
            type: DateTime<'U'>
        tsTo:
            type: DateTime<'U'>
        count:
            type: integer
        page:
            type: integer
        types:
            type: string
            access_type: public_method
            accessor:
                setter: setTypesFromString
                getter: getTypesAsString
